### ISSUE TITLE
`PaymentAccountResponse` not representative of the actual endpoint response

### ISSUE THREAD

**Issue by hardyrarso** [Midtrans/midtrans-go#17]
I'm trying to integrate this SDK into my current repository, previously I was using direct HTTP requests with my own client.

I'm a bit confused on the `PaymentAccountResponse` struct..

This struct has an `Action` field whereas the actual response of the endpoint has _actions_, plural. According to the docs and I checked the endpoint by testing it on sandbox, it actually returns `actions`, an array of `Action`.

I thought this was intentional but when I checked the code for `LinkPaymentAccount` method it just simply marshals the response into the struct. 

This probably means that the `Action` field will always be empty and that the actual `actions` will be ignored..?

Am I missing something here?

**Comment by Xaxxis** [comment]
Hi @hardyrarso thanks for reaching out to us. Looks like valid issue. We will take a look on this and get back to you. But if you already have the changes or fix, do not hesitate to open pull request. Thank you

**Comment by hardyrarso** [comment]
https://github.com/Midtrans/midtrans-go/pull/19

Just opened a PR. If you need me to change anything let me know. Thank you

**Comment by Xaxxis** [comment]
Hi @hardyrarso  we have merged your request and released a new version. We really appreciate your contribution. Thanks

If you have any general questions feel free to reach out us via [Midtrans Contact Us](https://midtrans.com/contact-us)
