### ISSUE TITLE
Installment Term Field in TransactionStatus when CheckTransaction

### ISSUE THREAD

**Issue by kevinkjs** [Midtrans/midtrans-go#21]
Hi, 

Can we get `installment_term` value from API response implemented in `TransactionStatus` when I use `CheckTransaction`? I need `installment_term` field on it since `check status` API also returned that field: 

```
{"masked_card":"47737760-1650","approval_code":"1662086003735","bank":"bca","eci":"05","installment_term":24,"channel_response_code":"0","channel_response_message":"Approved","three_ds_version":"1","transaction_time":"2022-09-02 09:33:08","gross_amount":"230000.00","currency":"IDR","order_id":"03-16620858337043","payment_type":"credit_card","signature_key":"2f217f1356725fb227ad8b35bc6db0349021def58326f5f6f6c5d2eca572a289c1a9ae6c7cd21d54b18e529ae76c3f3ddf2fe8aa05109f94332726dad2ed3b22","status_code":"200","transaction_id":"f997d6ba-af8c-4d31-b159-d74f522ca5d1","transaction_status":"capture","fraud_status":"accept","status_message":"Success, transaction is found","merchant_id":"G182508043","card_type":"credit"}
```

**Comment by Xaxxis** [comment]
Hi @kevinkjs thank you for reaching out to us. Seems valid issue. We will take a look on this and get back to you. But if you already have the changes or fix, do not hesitate to open pull request. Thank you

**Comment by Xaxxis** [comment]
Hi @kevinkjs added on this version ya [v1.3.5](https://github.com/Midtrans/midtrans-go/releases/tag/v1.3.5), Please kindly update your repo using the latest version. Thank you

**Comment by kevinkjs** [comment]
thanks @Xaxxis
