### ISSUE TITLE
CardPointInquiry Response Struct

### ISSUE THREAD

**Issue by erwinwahyura** [Midtrans/midtrans-go#23]
Hi, i just want to make sure the func `CardPointInquiry` its should be return struct like `CardPointInquiryResponse` instead of `CardTokenResponse` ?

```
type PointInquiryResponse struct {
	StatusCode         string `json:"status_code"`
	StatusMessage      string `json:"status_message"`
	PointBalance       int    `json:"point_balance"`
	TransactionTime    string `json:"transaction_time"`
	PointBalanceAmount string `json:"point_balance_amount"`
}
```

```
// CardPointInquiry : Do `/point_inquiry/{tokenId}` API request to Midtrans Core API return `coreapi.CardTokenResponse`,
// more detail refer to: https://api-docs.midtrans.com/#point-inquiry
func (c Client) CardPointInquiry(cardToken string) (*CardTokenResponse, *midtrans.Error) {
	resp := &CardTokenResponse{}
	err := c.HttpClient.Call(
		http.MethodGet,
		fmt.Sprintf("%s/v2/point_inquiry/%s", c.Env.BaseUrl(), cardToken),
		&c.ServerKey,
		c.Options,
		nil,
		resp,
	)

	if err != nil {
		return resp, err
	}
	return resp, nil
}

// CardPointInquiry : Do `/point_inquiry/{tokenId}` API request to Midtrans Core API return `coreapi.CardTokenResponse`,
// more detail refer to: https://api-docs.midtrans.com/#point-inquiry
func CardPointInquiry(cardToken string) (*CardTokenResponse, *midtrans.Error) {
	return getDefaultClient().CardPointInquiry(cardToken)
}
```

**Comment by Xaxxis** [comment]
Hi @erwinwahyura thank you for reaching out to us. Yes, it should be returned to struct `CardPointInquiryResponse`. Seems valid issue. We will take a look at this and get back to you. But if you already have the changes or fix, do not hesitate to open pull request. Thank you

**Comment by erwinwahyura** [comment]
Hi @Xaxxis cool opened PR at #24

**Comment by rizdaprasetya** [comment]
I'll help Zaki while he's currently away.

Approved, merged & published, thanks for reporting the issue & contributing mas @erwinwahyura ! 👍 appreciate it. Thanks!

Will close this for now. let us know if you find any other issues. Thanks

Internal notes: todo: may need to add tests for this function in the future
