### ISSUE TITLE
[OOT] GoPay on Payment Link API 

### ISSUE THREAD

**Issue by kokoraka** [Midtrans/midtrans-go#25]
Hi guys,

I wonder if I can use `gopay` on Payment Link API since you guys mention it on [payment link api doc](https://docs.midtrans.com/en/technical-reference/payment-link-api)
![image](https://user-images.githubusercontent.com/60498861/194823591-ca5f60cf-7031-4bf1-b9c1-f38b270edd3d.png)

When I try directly hit the payment link endpoint, the request is success but the payment link screen show "No channel available" :(

Payment link URL: https://app.sandbox.midtrans.com/payment-links/1665384920098

Regards

![image](https://user-images.githubusercontent.com/60498861/194823330-f6fa6624-e1c9-478e-8f50-0311b2ddfa8b.png)

*p.s: sorry for unrelated issue regarding the go midtrans sdk

**Comment by Xaxxis** [comment]
Hi @kokoraka seems your sandbox payment channel is already active now, could you help to retry? Also for any general question may you can reach out to our support team via [Midtrans Contact Us](https://midtrans.com/id/kontak-kami). Thank you

**Comment by kokoraka** [comment]
Yes @Xaxxis , thanks for the information
