### ISSUE TITLE
Validate Bank Account BRI always return success (Sandbox env)

### ISSUE THREAD

**Issue by klepon46** [Midtrans/midtrans-go#27]
Hi,

I always get success validated bank account whenever I fill bank with BRI and with random account number.

Curl:
`curl --location --request GET 'https://app.sandbox.midtrans.com/iris/api/v1/account_validation?bank=bri&account=4421321321321' \
--header 'Accept: application/json' \
--header 'Cache-Control: no-cache' \
--header 'Authorization: Basic KEY'`

Response:
`{"id":"62608a9a40bf4124b254f6a95be9023a","account_no":"4421321321321","bank_name":"bri","account_name":"BRI Simulator A"}`

**Comment by Xaxxis** [comment]
Hi, @klepon46 thank you for reaching out to us. It seems a valid issue on our API response but should impact on sandbox env. Will inform our payment team to check. I will inform you once the issue solve

Thank You

**Comment by klepon46** [comment]
Hi @Xaxxis Any updated?

**Comment by Xaxxis** [comment]
Hi, @klepon46 our team is still discussing this, but low priority because this is impacted only on Sandbox env. As a workaround, may you can use this BRI account number `888801000009999` to simulate an invalidated BRI bank account on the sandbox environment.

Thanks
