### ISSUE TITLE
got panic, res is nil when get error on c.HttpClient.Do(req)

### ISSUE THREAD

**Issue by fajrifernanda** [Midtrans/midtrans-go#7]
when http call is error (in my case deadline exceeded) res is nil and got panic on 102. is it possible get error and res is not nil? i think it will be good to add nil checker on res before get value res.StatusCode 

https://github.com/Midtrans/midtrans-go/blob/ad331a7696931825635e92a53472344936110792/httpclient.go#L97-L105

**Comment by Xaxxis** [comment]
Hi @fajrifernanda thank you for reaching out to us, will further check for this

> when http call is error (in my case deadline exceeded) res is nil and got panic on 102

Do you mean, when you got HTTP time out?

Thank you

**Comment by fajrifernanda** [comment]
yes on error HTTP time out

**Comment by Xaxxis** [comment]
Hi @fajrifernanda the issue has been solved on the [new version v1.2.2](https://github.com/Midtrans/midtrans-go/releases/tag/v1.2.2) ya

Thank you

**Comment by fajrifernanda** [comment]
nice, thanks
